[template]
include = ["Cargo.toml", "src/lib.rs"]
ignore = ["LICENSE", "README.md", "post_script.rhai"]

[placeholders]
ci_enabled = { type = "bool", prompt = "Enable Github CI?", default = true }
optimizations_enabled = { type = "bool", prompt = "Enable debug optimizations?", default = true }
android_enabled = { type = "bool", prompt = "Enable android target?", default = true }
ios_enabled = { type = "bool", prompt = "Enable iOS target?", default = true }
wasm_enabled = { type = "bool", prompt = "Enable WASM target?", default = true }

[conditional.'wasm_enabled'.placeholders]
wasm_resize_enabled = { type = "bool", prompt = "[WASM] Enable automatic window resize in browser?", default = true }
wasm_context_disabled = { type = "bool", prompt = "[WASM] Prevent context menu from showing on browser?", default = true }

[conditional.'ios_enabled'.placeholders]
ios_company_name = { type = "string", prompt = "[iOS] What is your company name? (used for the bundle)" }

[conditional.'!android_enabled']
ignore = ["assets/res"]

[conditional.'!wasm_enabled']
ignore = ["index.html", "build_wasm.sh"]

[conditional.'wasm_enabled']
include = ["index.html", "build_wasm.sh"]

[conditional.'!ci_enabled']
ignore = [".github"]

[conditional.'!ios_enabled']
ignore = ["apple", "assets/res"]

[conditional.'ios_enabled']
include = ["apple/Makefile", "apple/qoncealed.xcodeproj/project.pbxproj"]

[hooks]
post = ["post_script.rhai"]